### ISSUE TITLE
Is raylib 3.5 Compatible

### ISSUE THREAD

**Issue by Cronos87** [overdev/raylib-py#14]
Hello!

Is the library actually compatible with the new release of raylib 3.0?

Thank you for the answer!

**Comment by varomix** [comment]
Actually 3.5 is out now :)

**Comment by Cronos87** [comment]
Yes, indeed! I changed the title 😄

**Comment by adamlwgriffiths** [comment]
Check out the `raylibpy-3.7` branch.
