### ISSUE TITLE
Error when importing raylibpy

### ISSUE THREAD

**Issue by hunar1997** [overdev/raylib-py#16]
Hello, I really like raylib and it works without any problem in C
Today i wanted to use it inside python, I did`pip install raylib-py` then opened a python terminal to import it `import raylibpy` and i got this error message
![Screenshot_20200515_165743](https://user-images.githubusercontent.com/14861276/82059017-2a941a80-96ce-11ea-8208-a35b3a320d3e.png)
What does that error mean?

**Comment by KonPet** [comment]
I'm getting a similar error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<my_name>\AppData\Local\Programs\Python\Python38\lib\site-packages\raylibpy\__init__.py", line 56, in <module>
    second_path = os.path.dirname(sys.modules['__main__'].__file__)
AttributeError: module '__main__' has no attribute '__file__'
How can I fix it?

**Comment by rodneylives** [comment]
I also am having this issue. Windows 10, Python 3.8.

**Comment by dtomvan** [comment]
Same as @SkilLP, Python 3.8.6 on Windows 10 2004

**Comment by evanthomas** [comment]
Same, raspberry pi, python 3.7

**Comment by evanthomas** [comment]
You can might be able to work around it by setting the RAYLIB_BIN_PATH environment variable to point to the where library is installed since there will be binaries there. Unfortunately, only intel binaries are available. Apparently, ARM is not worth supporting.
