### ISSUE TITLE
Chinese encoding problem

### ISSUE THREAD

**Issue by tinc0709** [overdev/raylib-py#21]
how can i use chinese encode in raylib, I got this
![WechatIMG83](https://user-images.githubusercontent.com/13182485/106873955-fbb44d80-670f-11eb-8fa3-9a8ad2c24abd.png)

**Comment by tinc0709** [comment]
image does not work, but i need to fix the chinese encoding problem

**Comment by MangoDowner** [comment]
I met the same problem and don't know how to solve it...

**Comment by overdev** [comment]
This is related to C raylib.
