### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by RJGJ** [overdev/raylib-py#27]
I just followed the instructions an got this error.

`Traceback (most recent call last):
  File "G:\programming_projects\RaylibPyGame\main.py", line 5, in <module>
    import raylibpy
  File "G:\programming_projects\RaylibPyGame\.venv\lib\site-packages\raylibpy\__init__.py", line 71, in <module>
    _rl = CDLL(os.path.join(RAYLIB_BIN_PATH, _lib_filename[_platform]))
  File "C:\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application`

**Comment by Razikus** [comment]
Same here

**Comment by Jmacklin308** [comment]
I'm seeing the same thing on my side. This is happening with the example code in [the core 2D camera](https://github.com/overdev/raylib-py/blob/master/examples/core/core_2d_camera.py)

**Comment by adamlwgriffiths** [comment]
The code hasn't been updated to the latest. Trying to use a version of raylib beyond 2.0 results in an error.
At the moment [`raylib`](https://github.com/electronstudio/raylib-python-cffi) seems to be the only working wrapper.

**Comment by BrakingChanges** [comment]
Same thing even after 4 months of this issue

**Comment by adamlwgriffiths** [comment]
You should try out the [raylib-3.7](https://github.com/overdev/raylib-py/tree/raylibpy-3.7) branch.

Master is version 2.0.0 which is very old.
Momentum should be put toward the 3.7+ branch.
