### ISSUE TITLE
Model Texturing Bug

### ISSUE THREAD

**Issue by Pebaz** [overdev/raylib-py#3]
Problem Statement: `examples/models/models_heightmap.py` shows that textures are not applied when rendering models.

Raylib-C Equivalent Example (Shows darkened edges of the model due to texture used):
![image](https://user-images.githubusercontent.com/28033767/53702536-179d6f00-3dd6-11e9-9282-c7b4bca887ef.png)

Raylib-Py Example of Issue (Shows that the model is completely red instead of using the texture):
![image](https://user-images.githubusercontent.com/28033767/53702591-9f837900-3dd6-11e9-987a-f42330084ba0.png)

**Comment by Pebaz** [comment]
I have searched through the Raylib-Py source and as far as I can tell, all of the bindings are correctly structured. Functions that work are structured the exact same as the functions pertaining to this rendering bug. Not sure why a model using the same example code as Raylib-C would not show it's texture.

I will dig more into this. If you have thoughts on this please share them! 😄

**Comment by SolarLune** [comment]
Are your two builds of raylib using the same version? Maybe something was changed in the model drawing system to account for this.

**Comment by Pebaz** [comment]
Thanks for the idea!

I checked it out and found:

1. Raylib-C was using v2 MingW
2. Raylib-Py was using v2 MingW (But Python is MSVC...?)
3. Raylib-Py cannot see exposed functions contained in MSVC `raylib_shared.dll`
4. I even loaded the DLL into [DllExportViewer](http://www.nirsoft.net/utils/dll_export_viewer.html)and it cannot see any of the functions...

My best guess is that the Raylib 2.0 MSVC pre-compiled binary is somehow flawed if [DllExportViewer](http://www.nirsoft.net/utils/dll_export_viewer.html) cannot even see functions exposed within it.

I will try to compile Raylib on MSVC from source and see if I can get Python/[DllExportViewer](http://www.nirsoft.net/utils/dll_export_viewer.html) to see it.

-Sam

**Comment by Pebaz** [comment]
I compiled and tested the x64 MSVC version to to avail.  Not sure where to go from here.

**Comment by overdev** [comment]
Hi, @Pebaz! Sorry for the delay, didn't have much time lately to answer.

Oh, I don't have enough knowledge on compilers, build systems and stuff like this, and I have no idea if this might be the cause but the dll shipped with raylib-py is a custom one. I built it in my computer to add a few extra draw functions, wich will be officially available in the 2.5 release.

@SolarLune Thanks for the info! It is always good to have people who know better around. :sweat_smile:

**Comment by Pebaz** [comment]
No worries!

Has anyone gotten this particular example (`examples/models/models_heightmap.py`) to texture properly?

If someone has, maybe we can go from there (find out library, Python, and system architecture, what compiler, etc.).

**Comment by raysan5** [comment]
Not sure but this issue seems related to library versions mixing... latest raylib manages texturing in a different way than raylib 2.0...

**Comment by flipcoder** [comment]
I just did some investigating.  I traced the OpenGL calls of the program with the following line both commented and uncommented.

```
    model.material.maps[MAP_DIFFUSE].texture = texture
```

I rendered it for a single frame and diffed the two traces, no difference.

So that line seems to have no effect on raylib's rendering whatsoever.  Not sure how much this helps but it's more information.

**Comment by electronstudio** [comment]
Is there any version of raylib-py (or raylib dll) I can use that is able to texture models?  I don't need the latest advanced features but not having textures is something of a showstopper to my game development.

**Comment by Pebaz** [comment]
@electronstudio I was not able to get any version of the DLL to work.
As far as I am concerned, I cannot continue to use Raylib-Py without being able to texture a 3D model.
If anyone has been able to get this example to work, it would be helpful to hear from them.

**Comment by electronstudio** [comment]
Good news: I got it working.

![image](https://user-images.githubusercontent.com/7192452/58063245-43c6c180-7b75-11e9-8c6c-9179b8821cf4.png)

Bad news: I had to rewrite everything from scratch.

Will post it when I've cleaned up it.

**Comment by electronstudio** [comment]
Here: https://github.com/electronstudio/raylib-python-cffi

It works on my Mac and I've included the Mac binary but I don't have build systems setup for Windows and Linux.

**Comment by Pebaz** [comment]
Fantastic work!
