### ISSUE TITLE
Merge `raylibpy-3.7` to master

### ISSUE THREAD

**Issue by adamlwgriffiths** [overdev/raylib-py#35]
The current master branch is using an old version of raylib which is not API compatible with the latest 3.x branch.
The 3.7 branch seems to be working - although I  haven't exhaustively tested.
Are there any reasons to not merge 3.7 to master?

**Comment by overdev** [comment]
There is not a strong reason. What kept me from merging is that there is some major binding bugs I would like to solve first, like the ones in the shader and models examples. (I'm yet to push those.)

ATM I'm wrapping the rlgl layer, as it is used in some examples, and after that I'll finish the shader/models examples translation. When I'm done with these two things I'll merge to master.

Too bad that I've had so little time lately.

**Comment by adamlwgriffiths** [comment]
If you push what you've got to another branch (so we don't break what there is of 3.7 currently) I might be able to find some time to pitch in.

**Comment by overdev** [comment]
Well...  I couldn't do what I intended back in the day. Too bad. My bad.
