### ISSUE TITLE
Bug in `_color`?

### ISSUE THREAD

**Issue by mjoork** [overdev/raylib-py#42]
In the return it uses `r` for green as well. Is this a bug? Should I create a PR instead to solve this?
https://github.com/overdev/raylib-py/blob/786efdc332eb885a4a14b65cbf9bf3df6eef833f/raylibpy/core.py#L224-L229

# To reproduce

1. Get `raylibpy-3.7` branch installed
2. Write this code:
```python
from raylibpy.colors import *
from raylibpy.consts import *
from raylibpy.pythonic import *
from raylibpy.spartan import clear_background, drawing

window = Window(800, 600, "Sum title")

while not window.should_close:
    with drawing():
        clear_background((255, 0, 0, 255))
```
3. Run it

# Expectations

Screen is red

# Reality

Screen is yellow

**Comment by overdev** [comment]
Thanks!

Fixed in [v4.2.0.post1](https://github.com/overdev/raylib-py/releases/tag/v4.2.0.post1).
