### ISSUE TITLE
Has this repo been abandoned?

### ISSUE THREAD

**Issue by fabtjar** [overdev/raylib-py#44]
Hey this repo is linked to from the raylib homepage but it looks like master is only on 2.0 while 4.0 is the most recent version out. Just wondering is there a reason for this or does the owner not have the free time to keep it updated? Do you want others to contribute?

**Comment by BIueish** [comment]
There is another up to date binding: https://github.com/electronstudio/raylib-python-cffi

**Comment by overdev** [comment]
Sorry for not answering before.

The project still lives, kinda, but not here exactly.

As Blueish mentioned, there are other cool bindings around.

This repo is only for python package releases (wheels and sdists) wich are built from other repository's source code.
