### ISSUE TITLE
Binding tool

### ISSUE THREAD

**Issue by supreme-core** [overdev/raylib-py#9]
Hi,

Out of curiosity, what binding tool did you use to create your binding ? I am looking at pybind11 right now.

**Comment by overdev** [comment]
Hi, @supreme-core.

I did it the hard way. :laughing: In fact, I didn't used a tool, and didn't typed everything also. I copied the raylib.h and used the Search & Replace functionality of my editors of choice (Sublime Text and PyCharm) to the best of my ability, then I made some tweaks here and there, added some helper functions, classes etc.

This is my first successful binding, so I wanted to do it manually.
